# note: note useful for development (use webpack-dev-server)
# but could be useful to deploy to prod
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /public
  static_dir: public

- url: /.*
  static_files: index.html
  upload: index.html

skip_files:
- ^.*node_modules(/.*)?
- ^.*src(/.*)?