# note: note useful for development (use webpack-dev-server)
# but could be useful to deploy to prod
service: static

runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(.*)
  static_files: \1
  upload: /(.*)

skip_files:
- ^.*node_modules(/.*)?
